// Copyright 2023 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2024-09-16

package client

// EnvironmentRules EnvironmentRules is the authored source of truth for an environment: for each field, what a creator may choose and what value the environment supplies. Whether a question is asked is derived from the constraints; see each rule's semantics..
type EnvironmentRules struct {
	Allowlist        *AllowlistRule        `json:"allowlist,omitempty"`
	Cidr             *CidrRule             `json:"cidr,omitempty"`
	CloudAccount     *CloudAccountRule     `json:"cloud_account,omitempty"`
	Compute          *ComputeRule          `json:"compute,omitempty"`
	DeleteProtection *DeleteProtectionRule `json:"delete_protection,omitempty"`
	Folder           *FolderRule           `json:"folder,omitempty"`
	Labels           *LabelsRule           `json:"labels,omitempty"`
	Network          *NetworkRule          `json:"network,omitempty"`
	Provider         *CloudProviderType    `json:"provider,omitempty"`
	Regions          *RegionRule           `json:"regions,omitempty"`
}

// NewEnvironmentRules instantiates a new EnvironmentRules object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentRules() *EnvironmentRules {
	p := EnvironmentRules{}
	return &p
}

// GetAllowlist returns the Allowlist field value if set, zero value otherwise.
func (o *EnvironmentRules) GetAllowlist() AllowlistRule {
	if o == nil || o.Allowlist == nil {
		var ret AllowlistRule
		return ret
	}
	return *o.Allowlist
}

// SetAllowlist gets a reference to the given AllowlistRule and assigns it to the Allowlist field.
func (o *EnvironmentRules) SetAllowlist(v AllowlistRule) {
	o.Allowlist = &v
}

// GetCidr returns the Cidr field value if set, zero value otherwise.
func (o *EnvironmentRules) GetCidr() CidrRule {
	if o == nil || o.Cidr == nil {
		var ret CidrRule
		return ret
	}
	return *o.Cidr
}

// SetCidr gets a reference to the given CidrRule and assigns it to the Cidr field.
func (o *EnvironmentRules) SetCidr(v CidrRule) {
	o.Cidr = &v
}

// GetCloudAccount returns the CloudAccount field value if set, zero value otherwise.
func (o *EnvironmentRules) GetCloudAccount() CloudAccountRule {
	if o == nil || o.CloudAccount == nil {
		var ret CloudAccountRule
		return ret
	}
	return *o.CloudAccount
}

// SetCloudAccount gets a reference to the given CloudAccountRule and assigns it to the CloudAccount field.
func (o *EnvironmentRules) SetCloudAccount(v CloudAccountRule) {
	o.CloudAccount = &v
}

// GetCompute returns the Compute field value if set, zero value otherwise.
func (o *EnvironmentRules) GetCompute() ComputeRule {
	if o == nil || o.Compute == nil {
		var ret ComputeRule
		return ret
	}
	return *o.Compute
}

// SetCompute gets a reference to the given ComputeRule and assigns it to the Compute field.
func (o *EnvironmentRules) SetCompute(v ComputeRule) {
	o.Compute = &v
}

// GetDeleteProtection returns the DeleteProtection field value if set, zero value otherwise.
func (o *EnvironmentRules) GetDeleteProtection() DeleteProtectionRule {
	if o == nil || o.DeleteProtection == nil {
		var ret DeleteProtectionRule
		return ret
	}
	return *o.DeleteProtection
}

// SetDeleteProtection gets a reference to the given DeleteProtectionRule and assigns it to the DeleteProtection field.
func (o *EnvironmentRules) SetDeleteProtection(v DeleteProtectionRule) {
	o.DeleteProtection = &v
}

// GetFolder returns the Folder field value if set, zero value otherwise.
func (o *EnvironmentRules) GetFolder() FolderRule {
	if o == nil || o.Folder == nil {
		var ret FolderRule
		return ret
	}
	return *o.Folder
}

// SetFolder gets a reference to the given FolderRule and assigns it to the Folder field.
func (o *EnvironmentRules) SetFolder(v FolderRule) {
	o.Folder = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *EnvironmentRules) GetLabels() LabelsRule {
	if o == nil || o.Labels == nil {
		var ret LabelsRule
		return ret
	}
	return *o.Labels
}

// SetLabels gets a reference to the given LabelsRule and assigns it to the Labels field.
func (o *EnvironmentRules) SetLabels(v LabelsRule) {
	o.Labels = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *EnvironmentRules) GetNetwork() NetworkRule {
	if o == nil || o.Network == nil {
		var ret NetworkRule
		return ret
	}
	return *o.Network
}

// SetNetwork gets a reference to the given NetworkRule and assigns it to the Network field.
func (o *EnvironmentRules) SetNetwork(v NetworkRule) {
	o.Network = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *EnvironmentRules) GetProvider() CloudProviderType {
	if o == nil || o.Provider == nil {
		var ret CloudProviderType
		return ret
	}
	return *o.Provider
}

// SetProvider gets a reference to the given CloudProviderType and assigns it to the Provider field.
func (o *EnvironmentRules) SetProvider(v CloudProviderType) {
	o.Provider = &v
}

// GetRegions returns the Regions field value if set, zero value otherwise.
func (o *EnvironmentRules) GetRegions() RegionRule {
	if o == nil || o.Regions == nil {
		var ret RegionRule
		return ret
	}
	return *o.Regions
}

// SetRegions gets a reference to the given RegionRule and assigns it to the Regions field.
func (o *EnvironmentRules) SetRegions(v RegionRule) {
	o.Regions = &v
}
