// Copyright 2023 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2024-09-16

package client

// UpdateEnvironmentSpecification UpdateEnvironmentSpecification carries the mutable environment fields. Omitted fields are unchanged; PATCH with current contents is a no-op..
type UpdateEnvironmentSpecification struct {
	// description replaces the environment's description when set.
	Description *string `json:"description,omitempty"`
	// name replaces the environment's name when set.
	Name  *string           `json:"name,omitempty"`
	Rules *EnvironmentRules `json:"rules,omitempty"`
}

// NewUpdateEnvironmentSpecification instantiates a new UpdateEnvironmentSpecification object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateEnvironmentSpecification() *UpdateEnvironmentSpecification {
	p := UpdateEnvironmentSpecification{}
	return &p
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateEnvironmentSpecification) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateEnvironmentSpecification) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateEnvironmentSpecification) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateEnvironmentSpecification) SetName(v string) {
	o.Name = &v
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *UpdateEnvironmentSpecification) GetRules() EnvironmentRules {
	if o == nil || o.Rules == nil {
		var ret EnvironmentRules
		return ret
	}
	return *o.Rules
}

// SetRules gets a reference to the given EnvironmentRules and assigns it to the Rules field.
func (o *UpdateEnvironmentSpecification) SetRules(v EnvironmentRules) {
	o.Rules = &v
}
