// Copyright 2023 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2024-09-16

package client

// AllowlistRule AllowlistRule supplies IP allowlist entries created with the cluster. When present with no entries the cluster starts closed to public traffic. When absent the platform default applies (serverless starts open)..
type AllowlistRule struct {
	// entries are created with the cluster exactly as authored here; they are owned by the environment.
	Entries *[]AllowlistEntryRule `json:"entries,omitempty"`
	// settable permits the creator to supply additional entries, including their sql/ui flags.
	Settable *bool `json:"settable,omitempty"`
}

// NewAllowlistRule instantiates a new AllowlistRule object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAllowlistRule() *AllowlistRule {
	p := AllowlistRule{}
	return &p
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *AllowlistRule) GetEntries() []AllowlistEntryRule {
	if o == nil || o.Entries == nil {
		var ret []AllowlistEntryRule
		return ret
	}
	return *o.Entries
}

// SetEntries gets a reference to the given []AllowlistEntryRule and assigns it to the Entries field.
func (o *AllowlistRule) SetEntries(v []AllowlistEntryRule) {
	o.Entries = &v
}

// GetSettable returns the Settable field value if set, zero value otherwise.
func (o *AllowlistRule) GetSettable() bool {
	if o == nil || o.Settable == nil {
		var ret bool
		return ret
	}
	return *o.Settable
}

// SetSettable gets a reference to the given bool and assigns it to the Settable field.
func (o *AllowlistRule) SetSettable(v bool) {
	o.Settable = &v
}
