// Copyright 2023 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2024-09-16

package client

// UpdateClusterInEnvironmentBody struct for UpdateClusterInEnvironmentBody.
type UpdateClusterInEnvironmentBody struct {
	DeleteProtection *DeleteProtectionStateType `json:"delete_protection,omitempty"`
	// folder_id answers the folder question.
	FolderId *string `json:"folder_id,omitempty"`
	// labels are creator labels, merged under the environment's label rules.
	Labels *map[string]string `json:"labels,omitempty"`
	// regions answers the region question.
	Regions *[]string `json:"regions,omitempty"`
	// storage_gib answers the storage question (dedicated family only).
	StorageGib *int64 `json:"storage_gib,omitempty,string"`
	// vcpus answers the compute size question.
	Vcpus *int64 `json:"vcpus,omitempty,string"`
}

// NewUpdateClusterInEnvironmentBody instantiates a new UpdateClusterInEnvironmentBody object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateClusterInEnvironmentBody() *UpdateClusterInEnvironmentBody {
	p := UpdateClusterInEnvironmentBody{}
	return &p
}

// GetDeleteProtection returns the DeleteProtection field value if set, zero value otherwise.
func (o *UpdateClusterInEnvironmentBody) GetDeleteProtection() DeleteProtectionStateType {
	if o == nil || o.DeleteProtection == nil {
		var ret DeleteProtectionStateType
		return ret
	}
	return *o.DeleteProtection
}

// SetDeleteProtection gets a reference to the given DeleteProtectionStateType and assigns it to the DeleteProtection field.
func (o *UpdateClusterInEnvironmentBody) SetDeleteProtection(v DeleteProtectionStateType) {
	o.DeleteProtection = &v
}

// GetFolderId returns the FolderId field value if set, zero value otherwise.
func (o *UpdateClusterInEnvironmentBody) GetFolderId() string {
	if o == nil || o.FolderId == nil {
		var ret string
		return ret
	}
	return *o.FolderId
}

// SetFolderId gets a reference to the given string and assigns it to the FolderId field.
func (o *UpdateClusterInEnvironmentBody) SetFolderId(v string) {
	o.FolderId = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *UpdateClusterInEnvironmentBody) GetLabels() map[string]string {
	if o == nil || o.Labels == nil {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *UpdateClusterInEnvironmentBody) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetRegions returns the Regions field value if set, zero value otherwise.
func (o *UpdateClusterInEnvironmentBody) GetRegions() []string {
	if o == nil || o.Regions == nil {
		var ret []string
		return ret
	}
	return *o.Regions
}

// SetRegions gets a reference to the given []string and assigns it to the Regions field.
func (o *UpdateClusterInEnvironmentBody) SetRegions(v []string) {
	o.Regions = &v
}

// GetStorageGib returns the StorageGib field value if set, zero value otherwise.
func (o *UpdateClusterInEnvironmentBody) GetStorageGib() int64 {
	if o == nil || o.StorageGib == nil {
		var ret int64
		return ret
	}
	return *o.StorageGib
}

// SetStorageGib gets a reference to the given int64 and assigns it to the StorageGib field.
func (o *UpdateClusterInEnvironmentBody) SetStorageGib(v int64) {
	o.StorageGib = &v
}

// GetVcpus returns the Vcpus field value if set, zero value otherwise.
func (o *UpdateClusterInEnvironmentBody) GetVcpus() int64 {
	if o == nil || o.Vcpus == nil {
		var ret int64
		return ret
	}
	return *o.Vcpus
}

// SetVcpus gets a reference to the given int64 and assigns it to the Vcpus field.
func (o *UpdateClusterInEnvironmentBody) SetVcpus(v int64) {
	o.Vcpus = &v
}
