// Copyright 2023 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2024-09-16

package client

// RegionRule RegionRule constrains and defaults the regions of clusters created in an environment. Empty allowed means any region the environment's provider offers. Exactly one allowed region means the environment owns the choice..
type RegionRule struct {
	// allowed lists the permitted regions of the environment's provider.
	Allowed *[]string `json:"allowed,omitempty"`
	// default is preselected when the question is asked; it must be a subset of allowed when allowed is non-empty.
	Default *[]string `json:"default,omitempty"`
	// max_region_count caps regions per cluster; 1 means single-region only; 0 means no cap.
	MaxRegionCount *int32 `json:"max_region_count,omitempty"`
}

// NewRegionRule instantiates a new RegionRule object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegionRule() *RegionRule {
	p := RegionRule{}
	return &p
}

// GetAllowed returns the Allowed field value if set, zero value otherwise.
func (o *RegionRule) GetAllowed() []string {
	if o == nil || o.Allowed == nil {
		var ret []string
		return ret
	}
	return *o.Allowed
}

// SetAllowed gets a reference to the given []string and assigns it to the Allowed field.
func (o *RegionRule) SetAllowed(v []string) {
	o.Allowed = &v
}

// GetDefault returns the Default field value if set, zero value otherwise.
func (o *RegionRule) GetDefault() []string {
	if o == nil || o.Default == nil {
		var ret []string
		return ret
	}
	return *o.Default
}

// SetDefault gets a reference to the given []string and assigns it to the Default field.
func (o *RegionRule) SetDefault(v []string) {
	o.Default = &v
}

// GetMaxRegionCount returns the MaxRegionCount field value if set, zero value otherwise.
func (o *RegionRule) GetMaxRegionCount() int32 {
	if o == nil || o.MaxRegionCount == nil {
		var ret int32
		return ret
	}
	return *o.MaxRegionCount
}

// SetMaxRegionCount gets a reference to the given int32 and assigns it to the MaxRegionCount field.
func (o *RegionRule) SetMaxRegionCount(v int32) {
	o.MaxRegionCount = &v
}
