// Copyright 2023 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2024-09-16

package client

// LabelsRule LabelsRule supplies and constrains cluster labels..
type LabelsRule struct {
	// allow_other_labels permits creator labels on keys not listed in constraints.
	AllowOtherLabels *bool `json:"allow_other_labels,omitempty"`
	// constraints govern specific creator label keys.
	Constraints *[]LabelConstraint `json:"constraints,omitempty"`
	// supplied labels are stamped on every cluster created in the environment and win key collisions with creator labels.
	Supplied *map[string]string `json:"supplied,omitempty"`
}

// NewLabelsRule instantiates a new LabelsRule object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLabelsRule() *LabelsRule {
	p := LabelsRule{}
	return &p
}

// GetAllowOtherLabels returns the AllowOtherLabels field value if set, zero value otherwise.
func (o *LabelsRule) GetAllowOtherLabels() bool {
	if o == nil || o.AllowOtherLabels == nil {
		var ret bool
		return ret
	}
	return *o.AllowOtherLabels
}

// SetAllowOtherLabels gets a reference to the given bool and assigns it to the AllowOtherLabels field.
func (o *LabelsRule) SetAllowOtherLabels(v bool) {
	o.AllowOtherLabels = &v
}

// GetConstraints returns the Constraints field value if set, zero value otherwise.
func (o *LabelsRule) GetConstraints() []LabelConstraint {
	if o == nil || o.Constraints == nil {
		var ret []LabelConstraint
		return ret
	}
	return *o.Constraints
}

// SetConstraints gets a reference to the given []LabelConstraint and assigns it to the Constraints field.
func (o *LabelsRule) SetConstraints(v []LabelConstraint) {
	o.Constraints = &v
}

// GetSupplied returns the Supplied field value if set, zero value otherwise.
func (o *LabelsRule) GetSupplied() map[string]string {
	if o == nil || o.Supplied == nil {
		var ret map[string]string
		return ret
	}
	return *o.Supplied
}

// SetSupplied gets a reference to the given map[string]string and assigns it to the Supplied field.
func (o *LabelsRule) SetSupplied(v map[string]string) {
	o.Supplied = &v
}
