// Copyright 2023 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2024-09-16

package client

// ComputeRule ComputeRule bounds and defaults cluster compute. min == max owns the value..
type ComputeRule struct {
	// default_storage_gib is used when storage is not asked or not answered.
	DefaultStorageGib *int64 `json:"default_storage_gib,omitempty,string"`
	// default_vcpus is preselected when the question is asked.
	DefaultVcpus *int64 `json:"default_vcpus,omitempty,string"`
	// isolation_allowed constrains the isolation level. Empty means both; exactly one value means the environment owns it. Owning DEDICATED forces dedicated hardware even for public clusters.
	IsolationAllowed *[]ComputeIsolationType `json:"isolation_allowed,omitempty"`
	IsolationDefault *ComputeIsolationType   `json:"isolation_default,omitempty"`
	// max_storage_gib bounds per-node storage; 0 means unbounded above.
	MaxStorageGib *int64 `json:"max_storage_gib,omitempty,string"`
	// max_vcpus is the maximum vCPU count per cluster. 0 means unbounded above.
	MaxVcpus *int64 `json:"max_vcpus,omitempty,string"`
	// min_storage_gib bounds per-node storage; only meaningful when the family resolves dedicated. 0 means unbounded below.
	MinStorageGib *int64 `json:"min_storage_gib,omitempty,string"`
	// min_vcpus is the minimum vCPU count per cluster (provisioned vCPUs on serverless, machine vCPUs on dedicated). 0 means unbounded below.
	MinVcpus *int64 `json:"min_vcpus,omitempty,string"`
}

// NewComputeRule instantiates a new ComputeRule object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComputeRule() *ComputeRule {
	p := ComputeRule{}
	return &p
}

// GetDefaultStorageGib returns the DefaultStorageGib field value if set, zero value otherwise.
func (o *ComputeRule) GetDefaultStorageGib() int64 {
	if o == nil || o.DefaultStorageGib == nil {
		var ret int64
		return ret
	}
	return *o.DefaultStorageGib
}

// SetDefaultStorageGib gets a reference to the given int64 and assigns it to the DefaultStorageGib field.
func (o *ComputeRule) SetDefaultStorageGib(v int64) {
	o.DefaultStorageGib = &v
}

// GetDefaultVcpus returns the DefaultVcpus field value if set, zero value otherwise.
func (o *ComputeRule) GetDefaultVcpus() int64 {
	if o == nil || o.DefaultVcpus == nil {
		var ret int64
		return ret
	}
	return *o.DefaultVcpus
}

// SetDefaultVcpus gets a reference to the given int64 and assigns it to the DefaultVcpus field.
func (o *ComputeRule) SetDefaultVcpus(v int64) {
	o.DefaultVcpus = &v
}

// GetIsolationAllowed returns the IsolationAllowed field value if set, zero value otherwise.
func (o *ComputeRule) GetIsolationAllowed() []ComputeIsolationType {
	if o == nil || o.IsolationAllowed == nil {
		var ret []ComputeIsolationType
		return ret
	}
	return *o.IsolationAllowed
}

// SetIsolationAllowed gets a reference to the given []ComputeIsolationType and assigns it to the IsolationAllowed field.
func (o *ComputeRule) SetIsolationAllowed(v []ComputeIsolationType) {
	o.IsolationAllowed = &v
}

// GetIsolationDefault returns the IsolationDefault field value if set, zero value otherwise.
func (o *ComputeRule) GetIsolationDefault() ComputeIsolationType {
	if o == nil || o.IsolationDefault == nil {
		var ret ComputeIsolationType
		return ret
	}
	return *o.IsolationDefault
}

// SetIsolationDefault gets a reference to the given ComputeIsolationType and assigns it to the IsolationDefault field.
func (o *ComputeRule) SetIsolationDefault(v ComputeIsolationType) {
	o.IsolationDefault = &v
}

// GetMaxStorageGib returns the MaxStorageGib field value if set, zero value otherwise.
func (o *ComputeRule) GetMaxStorageGib() int64 {
	if o == nil || o.MaxStorageGib == nil {
		var ret int64
		return ret
	}
	return *o.MaxStorageGib
}

// SetMaxStorageGib gets a reference to the given int64 and assigns it to the MaxStorageGib field.
func (o *ComputeRule) SetMaxStorageGib(v int64) {
	o.MaxStorageGib = &v
}

// GetMaxVcpus returns the MaxVcpus field value if set, zero value otherwise.
func (o *ComputeRule) GetMaxVcpus() int64 {
	if o == nil || o.MaxVcpus == nil {
		var ret int64
		return ret
	}
	return *o.MaxVcpus
}

// SetMaxVcpus gets a reference to the given int64 and assigns it to the MaxVcpus field.
func (o *ComputeRule) SetMaxVcpus(v int64) {
	o.MaxVcpus = &v
}

// GetMinStorageGib returns the MinStorageGib field value if set, zero value otherwise.
func (o *ComputeRule) GetMinStorageGib() int64 {
	if o == nil || o.MinStorageGib == nil {
		var ret int64
		return ret
	}
	return *o.MinStorageGib
}

// SetMinStorageGib gets a reference to the given int64 and assigns it to the MinStorageGib field.
func (o *ComputeRule) SetMinStorageGib(v int64) {
	o.MinStorageGib = &v
}

// GetMinVcpus returns the MinVcpus field value if set, zero value otherwise.
func (o *ComputeRule) GetMinVcpus() int64 {
	if o == nil || o.MinVcpus == nil {
		var ret int64
		return ret
	}
	return *o.MinVcpus
}

// SetMinVcpus gets a reference to the given int64 and assigns it to the MinVcpus field.
func (o *ComputeRule) SetMinVcpus(v int64) {
	o.MinVcpus = &v
}
