// Copyright 2023 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2024-09-16

package client

// AllowlistEntryRule AllowlistEntryRule is one IP allowlist entry an environment supplies or a creator adds. At least one of sql or ui must be set..
type AllowlistEntryRule struct {
	// cidr is the entry in \"ip/mask\" form; a bare IP means /32. Include \"0.0.0.0/0\" for open-to-all.
	Cidr *string `json:"cidr,omitempty"`
	// sql grants SQL access from the range.
	Sql *bool `json:"sql,omitempty"`
	// ui grants DB Console access from the range.
	Ui *bool `json:"ui,omitempty"`
}

// NewAllowlistEntryRule instantiates a new AllowlistEntryRule object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAllowlistEntryRule() *AllowlistEntryRule {
	p := AllowlistEntryRule{}
	return &p
}

// GetCidr returns the Cidr field value if set, zero value otherwise.
func (o *AllowlistEntryRule) GetCidr() string {
	if o == nil || o.Cidr == nil {
		var ret string
		return ret
	}
	return *o.Cidr
}

// SetCidr gets a reference to the given string and assigns it to the Cidr field.
func (o *AllowlistEntryRule) SetCidr(v string) {
	o.Cidr = &v
}

// GetSql returns the Sql field value if set, zero value otherwise.
func (o *AllowlistEntryRule) GetSql() bool {
	if o == nil || o.Sql == nil {
		var ret bool
		return ret
	}
	return *o.Sql
}

// SetSql gets a reference to the given bool and assigns it to the Sql field.
func (o *AllowlistEntryRule) SetSql(v bool) {
	o.Sql = &v
}

// GetUi returns the Ui field value if set, zero value otherwise.
func (o *AllowlistEntryRule) GetUi() bool {
	if o == nil || o.Ui == nil {
		var ret bool
		return ret
	}
	return *o.Ui
}

// SetUi gets a reference to the given bool and assigns it to the Ui field.
func (o *AllowlistEntryRule) SetUi(v bool) {
	o.Ui = &v
}
