// Copyright 2023 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2024-09-16

package client

// NetworkRule NetworkRule constrains and defaults cluster network posture..
type NetworkRule struct {
	RestrictEgressTraffic *BoolRule `json:"restrict_egress_traffic,omitempty"`
	// visibility_allowed constrains network visibility. Empty means both; exactly one value means the environment owns it. PRIVATE forces the dedicated family.
	VisibilityAllowed *[]NetworkVisibilityType `json:"visibility_allowed,omitempty"`
	VisibilityDefault *NetworkVisibilityType   `json:"visibility_default,omitempty"`
}

// NewNetworkRule instantiates a new NetworkRule object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkRule() *NetworkRule {
	p := NetworkRule{}
	return &p
}

// GetRestrictEgressTraffic returns the RestrictEgressTraffic field value if set, zero value otherwise.
func (o *NetworkRule) GetRestrictEgressTraffic() BoolRule {
	if o == nil || o.RestrictEgressTraffic == nil {
		var ret BoolRule
		return ret
	}
	return *o.RestrictEgressTraffic
}

// SetRestrictEgressTraffic gets a reference to the given BoolRule and assigns it to the RestrictEgressTraffic field.
func (o *NetworkRule) SetRestrictEgressTraffic(v BoolRule) {
	o.RestrictEgressTraffic = &v
}

// GetVisibilityAllowed returns the VisibilityAllowed field value if set, zero value otherwise.
func (o *NetworkRule) GetVisibilityAllowed() []NetworkVisibilityType {
	if o == nil || o.VisibilityAllowed == nil {
		var ret []NetworkVisibilityType
		return ret
	}
	return *o.VisibilityAllowed
}

// SetVisibilityAllowed gets a reference to the given []NetworkVisibilityType and assigns it to the VisibilityAllowed field.
func (o *NetworkRule) SetVisibilityAllowed(v []NetworkVisibilityType) {
	o.VisibilityAllowed = &v
}

// GetVisibilityDefault returns the VisibilityDefault field value if set, zero value otherwise.
func (o *NetworkRule) GetVisibilityDefault() NetworkVisibilityType {
	if o == nil || o.VisibilityDefault == nil {
		var ret NetworkVisibilityType
		return ret
	}
	return *o.VisibilityDefault
}

// SetVisibilityDefault gets a reference to the given NetworkVisibilityType and assigns it to the VisibilityDefault field.
func (o *NetworkRule) SetVisibilityDefault(v NetworkVisibilityType) {
	o.VisibilityDefault = &v
}
