// Copyright 2023 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2024-09-16

package client

// CreateClusterInEnvironmentBody struct for CreateClusterInEnvironmentBody.
type CreateClusterInEnvironmentBody struct {
	// allowlist_entries are additional entries, when the allowlist is settable.
	AllowlistEntries *[]AllowlistEntryRule `json:"allowlist_entries,omitempty"`
	// cidr_range overrides the network range, when the cidr rule is settable.
	CidrRange        *string                    `json:"cidr_range,omitempty"`
	CloudAccount     *CustomerCloudAccount      `json:"cloud_account,omitempty"`
	DeleteProtection *DeleteProtectionStateType `json:"delete_protection,omitempty"`
	// folder_id answers the folder question.
	FolderId  *string               `json:"folder_id,omitempty"`
	Isolation *ComputeIsolationType `json:"isolation,omitempty"`
	// labels are creator labels, merged under the environment's label rules.
	Labels *map[string]string `json:"labels,omitempty"`
	// name follows the same constraints as CreateClusterRequest.name.
	Name              string                 `json:"name"`
	NetworkVisibility *NetworkVisibilityType `json:"network_visibility,omitempty"`
	// regions answers the region question.
	Regions *[]string `json:"regions,omitempty"`
	// restrict_egress_traffic answers the egress question.
	RestrictEgressTraffic *bool `json:"restrict_egress_traffic,omitempty"`
	// storage_gib answers the storage question (dedicated family only).
	StorageGib *int64 `json:"storage_gib,omitempty,string"`
	// vcpus answers the compute size question.
	Vcpus *int64 `json:"vcpus,omitempty,string"`
}

// NewCreateClusterInEnvironmentBody instantiates a new CreateClusterInEnvironmentBody object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClusterInEnvironmentBody(name string) *CreateClusterInEnvironmentBody {
	p := CreateClusterInEnvironmentBody{}
	p.Name = name
	return &p
}

// NewCreateClusterInEnvironmentBodyWithDefaults instantiates a new CreateClusterInEnvironmentBody object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClusterInEnvironmentBodyWithDefaults() *CreateClusterInEnvironmentBody {
	p := CreateClusterInEnvironmentBody{}
	return &p
}

// GetAllowlistEntries returns the AllowlistEntries field value if set, zero value otherwise.
func (o *CreateClusterInEnvironmentBody) GetAllowlistEntries() []AllowlistEntryRule {
	if o == nil || o.AllowlistEntries == nil {
		var ret []AllowlistEntryRule
		return ret
	}
	return *o.AllowlistEntries
}

// SetAllowlistEntries gets a reference to the given []AllowlistEntryRule and assigns it to the AllowlistEntries field.
func (o *CreateClusterInEnvironmentBody) SetAllowlistEntries(v []AllowlistEntryRule) {
	o.AllowlistEntries = &v
}

// GetCidrRange returns the CidrRange field value if set, zero value otherwise.
func (o *CreateClusterInEnvironmentBody) GetCidrRange() string {
	if o == nil || o.CidrRange == nil {
		var ret string
		return ret
	}
	return *o.CidrRange
}

// SetCidrRange gets a reference to the given string and assigns it to the CidrRange field.
func (o *CreateClusterInEnvironmentBody) SetCidrRange(v string) {
	o.CidrRange = &v
}

// GetCloudAccount returns the CloudAccount field value if set, zero value otherwise.
func (o *CreateClusterInEnvironmentBody) GetCloudAccount() CustomerCloudAccount {
	if o == nil || o.CloudAccount == nil {
		var ret CustomerCloudAccount
		return ret
	}
	return *o.CloudAccount
}

// SetCloudAccount gets a reference to the given CustomerCloudAccount and assigns it to the CloudAccount field.
func (o *CreateClusterInEnvironmentBody) SetCloudAccount(v CustomerCloudAccount) {
	o.CloudAccount = &v
}

// GetDeleteProtection returns the DeleteProtection field value if set, zero value otherwise.
func (o *CreateClusterInEnvironmentBody) GetDeleteProtection() DeleteProtectionStateType {
	if o == nil || o.DeleteProtection == nil {
		var ret DeleteProtectionStateType
		return ret
	}
	return *o.DeleteProtection
}

// SetDeleteProtection gets a reference to the given DeleteProtectionStateType and assigns it to the DeleteProtection field.
func (o *CreateClusterInEnvironmentBody) SetDeleteProtection(v DeleteProtectionStateType) {
	o.DeleteProtection = &v
}

// GetFolderId returns the FolderId field value if set, zero value otherwise.
func (o *CreateClusterInEnvironmentBody) GetFolderId() string {
	if o == nil || o.FolderId == nil {
		var ret string
		return ret
	}
	return *o.FolderId
}

// SetFolderId gets a reference to the given string and assigns it to the FolderId field.
func (o *CreateClusterInEnvironmentBody) SetFolderId(v string) {
	o.FolderId = &v
}

// GetIsolation returns the Isolation field value if set, zero value otherwise.
func (o *CreateClusterInEnvironmentBody) GetIsolation() ComputeIsolationType {
	if o == nil || o.Isolation == nil {
		var ret ComputeIsolationType
		return ret
	}
	return *o.Isolation
}

// SetIsolation gets a reference to the given ComputeIsolationType and assigns it to the Isolation field.
func (o *CreateClusterInEnvironmentBody) SetIsolation(v ComputeIsolationType) {
	o.Isolation = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *CreateClusterInEnvironmentBody) GetLabels() map[string]string {
	if o == nil || o.Labels == nil {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *CreateClusterInEnvironmentBody) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetName returns the Name field value.
func (o *CreateClusterInEnvironmentBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// SetName sets field value.
func (o *CreateClusterInEnvironmentBody) SetName(v string) {
	o.Name = v
}

// GetNetworkVisibility returns the NetworkVisibility field value if set, zero value otherwise.
func (o *CreateClusterInEnvironmentBody) GetNetworkVisibility() NetworkVisibilityType {
	if o == nil || o.NetworkVisibility == nil {
		var ret NetworkVisibilityType
		return ret
	}
	return *o.NetworkVisibility
}

// SetNetworkVisibility gets a reference to the given NetworkVisibilityType and assigns it to the NetworkVisibility field.
func (o *CreateClusterInEnvironmentBody) SetNetworkVisibility(v NetworkVisibilityType) {
	o.NetworkVisibility = &v
}

// GetRegions returns the Regions field value if set, zero value otherwise.
func (o *CreateClusterInEnvironmentBody) GetRegions() []string {
	if o == nil || o.Regions == nil {
		var ret []string
		return ret
	}
	return *o.Regions
}

// SetRegions gets a reference to the given []string and assigns it to the Regions field.
func (o *CreateClusterInEnvironmentBody) SetRegions(v []string) {
	o.Regions = &v
}

// GetRestrictEgressTraffic returns the RestrictEgressTraffic field value if set, zero value otherwise.
func (o *CreateClusterInEnvironmentBody) GetRestrictEgressTraffic() bool {
	if o == nil || o.RestrictEgressTraffic == nil {
		var ret bool
		return ret
	}
	return *o.RestrictEgressTraffic
}

// SetRestrictEgressTraffic gets a reference to the given bool and assigns it to the RestrictEgressTraffic field.
func (o *CreateClusterInEnvironmentBody) SetRestrictEgressTraffic(v bool) {
	o.RestrictEgressTraffic = &v
}

// GetStorageGib returns the StorageGib field value if set, zero value otherwise.
func (o *CreateClusterInEnvironmentBody) GetStorageGib() int64 {
	if o == nil || o.StorageGib == nil {
		var ret int64
		return ret
	}
	return *o.StorageGib
}

// SetStorageGib gets a reference to the given int64 and assigns it to the StorageGib field.
func (o *CreateClusterInEnvironmentBody) SetStorageGib(v int64) {
	o.StorageGib = &v
}

// GetVcpus returns the Vcpus field value if set, zero value otherwise.
func (o *CreateClusterInEnvironmentBody) GetVcpus() int64 {
	if o == nil || o.Vcpus == nil {
		var ret int64
		return ret
	}
	return *o.Vcpus
}

// SetVcpus gets a reference to the given int64 and assigns it to the Vcpus field.
func (o *CreateClusterInEnvironmentBody) SetVcpus(v int64) {
	o.Vcpus = &v
}
