// Copyright 2023 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2024-09-16

package client

// CreateEnvironmentRequest struct for CreateEnvironmentRequest.
type CreateEnvironmentRequest struct {
	// description should say when to use this environment.
	Description *string `json:"description,omitempty"`
	// name is unique within the organization.
	Name  string           `json:"name"`
	Rules EnvironmentRules `json:"rules"`
}

// NewCreateEnvironmentRequest instantiates a new CreateEnvironmentRequest object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEnvironmentRequest(name string, rules EnvironmentRules) *CreateEnvironmentRequest {
	p := CreateEnvironmentRequest{}
	p.Name = name
	p.Rules = rules
	return &p
}

// NewCreateEnvironmentRequestWithDefaults instantiates a new CreateEnvironmentRequest object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEnvironmentRequestWithDefaults() *CreateEnvironmentRequest {
	p := CreateEnvironmentRequest{}
	return &p
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateEnvironmentRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateEnvironmentRequest) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value.
func (o *CreateEnvironmentRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// SetName sets field value.
func (o *CreateEnvironmentRequest) SetName(v string) {
	o.Name = v
}

// GetRules returns the Rules field value.
func (o *CreateEnvironmentRequest) GetRules() EnvironmentRules {
	if o == nil {
		var ret EnvironmentRules
		return ret
	}

	return o.Rules
}

// SetRules sets field value.
func (o *CreateEnvironmentRequest) SetRules(v EnvironmentRules) {
	o.Rules = v
}
