// Copyright 2023 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2024-09-16

package client

// CloudAccountRule CloudAccountRule supplies and optionally exposes the customer cloud account. The zero state (no value, not settable) means customer cloud accounts are not on offer and clusters are fully managed..
type CloudAccountRule struct {
	// settable permits the creator to supply a customer cloud account.
	Settable *bool                 `json:"settable,omitempty"`
	Value    *CustomerCloudAccount `json:"value,omitempty"`
}

// NewCloudAccountRule instantiates a new CloudAccountRule object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudAccountRule() *CloudAccountRule {
	p := CloudAccountRule{}
	return &p
}

// GetSettable returns the Settable field value if set, zero value otherwise.
func (o *CloudAccountRule) GetSettable() bool {
	if o == nil || o.Settable == nil {
		var ret bool
		return ret
	}
	return *o.Settable
}

// SetSettable gets a reference to the given bool and assigns it to the Settable field.
func (o *CloudAccountRule) SetSettable(v bool) {
	o.Settable = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CloudAccountRule) GetValue() CustomerCloudAccount {
	if o == nil || o.Value == nil {
		var ret CustomerCloudAccount
		return ret
	}
	return *o.Value
}

// SetValue gets a reference to the given CustomerCloudAccount and assigns it to the Value field.
func (o *CloudAccountRule) SetValue(v CustomerCloudAccount) {
	o.Value = &v
}
