// Copyright 2023 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2024-09-16

package client

import (
	"time"
)

// Environment Environment is a named, org-level set of rules over cluster creation and update. Creators pick an environment, answer the questions its creation_spec asks, and the rules answer everything else..
type Environment struct {
	// created_at is when the environment was created.
	CreatedAt time.Time `json:"created_at"`
	// creation_spec is a JSON Schema (draft 2020-12) document describing the CreateClusterInEnvironment request body this environment accepts: one property per asked question plus name; environment-owned questions are absent. required lists only the fields whose omission makes creation fail. Derived from rules at read time; output only.
	CreationSpec map[string]interface{} `json:"creation_spec"`
	// description should say when to use this environment, not what it configures.
	Description string `json:"description"`
	// id uniquely identifies the environment.
	Id string `json:"id"`
	// name is unique within the organization. Choose names creators can pick from alone, using knowledge they already have (dev, staging, prod).
	Name  string           `json:"name"`
	Rules EnvironmentRules `json:"rules"`
	// update_spec is the same schema restricted to the fields UpdateClusterInEnvironment supports. It carries no defaults and no required list: omitting a field in an update leaves it unchanged. Derived from rules at read time; output only.
	UpdateSpec map[string]interface{} `json:"update_spec"`
	// updated_at is when the environment was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// NewEnvironment instantiates a new Environment object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironment(createdAt time.Time, creationSpec map[string]interface{}, description string, id string, name string, rules EnvironmentRules, updateSpec map[string]interface{}, updatedAt time.Time) *Environment {
	p := Environment{}
	p.CreatedAt = createdAt
	p.CreationSpec = creationSpec
	p.Description = description
	p.Id = id
	p.Name = name
	p.Rules = rules
	p.UpdateSpec = updateSpec
	p.UpdatedAt = updatedAt
	return &p
}

// NewEnvironmentWithDefaults instantiates a new Environment object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentWithDefaults() *Environment {
	p := Environment{}
	return &p
}

// GetCreatedAt returns the CreatedAt field value.
func (o *Environment) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// SetCreatedAt sets field value.
func (o *Environment) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetCreationSpec returns the CreationSpec field value.
func (o *Environment) GetCreationSpec() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.CreationSpec
}

// SetCreationSpec sets field value.
func (o *Environment) SetCreationSpec(v map[string]interface{}) {
	o.CreationSpec = v
}

// GetDescription returns the Description field value.
func (o *Environment) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// SetDescription sets field value.
func (o *Environment) SetDescription(v string) {
	o.Description = v
}

// GetId returns the Id field value.
func (o *Environment) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// SetId sets field value.
func (o *Environment) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value.
func (o *Environment) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// SetName sets field value.
func (o *Environment) SetName(v string) {
	o.Name = v
}

// GetRules returns the Rules field value.
func (o *Environment) GetRules() EnvironmentRules {
	if o == nil {
		var ret EnvironmentRules
		return ret
	}

	return o.Rules
}

// SetRules sets field value.
func (o *Environment) SetRules(v EnvironmentRules) {
	o.Rules = v
}

// GetUpdateSpec returns the UpdateSpec field value.
func (o *Environment) GetUpdateSpec() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.UpdateSpec
}

// SetUpdateSpec sets field value.
func (o *Environment) SetUpdateSpec(v map[string]interface{}) {
	o.UpdateSpec = v
}

// GetUpdatedAt returns the UpdatedAt field value.
func (o *Environment) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// SetUpdatedAt sets field value.
func (o *Environment) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}
