// Copyright 2023 The Cockroach Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// CockroachDB Cloud API
// API version: 2024-09-16

package client

// BoolRule BoolRule constrains a yes/no field. Empty allowed means both values are permitted and the question is asked; exactly one value owns the field..
type BoolRule struct {
	// allowed lists the permitted values (at most two).
	Allowed *[]bool `json:"allowed,omitempty"`
	// default is preselected when the question is asked.
	Default *bool `json:"default,omitempty"`
}

// NewBoolRule instantiates a new BoolRule object.
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBoolRule() *BoolRule {
	p := BoolRule{}
	return &p
}

// GetAllowed returns the Allowed field value if set, zero value otherwise.
func (o *BoolRule) GetAllowed() []bool {
	if o == nil || o.Allowed == nil {
		var ret []bool
		return ret
	}
	return *o.Allowed
}

// SetAllowed gets a reference to the given []bool and assigns it to the Allowed field.
func (o *BoolRule) SetAllowed(v []bool) {
	o.Allowed = &v
}

// GetDefault returns the Default field value if set, zero value otherwise.
func (o *BoolRule) GetDefault() bool {
	if o == nil || o.Default == nil {
		var ret bool
		return ret
	}
	return *o.Default
}

// SetDefault gets a reference to the given bool and assigns it to the Default field.
func (o *BoolRule) SetDefault(v bool) {
	o.Default = &v
}
